# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    
    - name: Deploy staging
      if: github.ref == 'refs/heads/staging'
      run: cp -r /home/mwakatumbula/deploy/deploy/webapp/webapp/ /home/mwakatumbula/staging
      
    - name: Change permissions 
      if: github.ref == 'refs/heads/staging'
      run: chmod -R 777 /home/mwakatumbula/staging
 
      
    - name: Deploy production
      if: github.ref == 'refs/heads/master'
      run: cp -r /home/mwakatumbula/deploy/deploy/webapp/webapp/ /home/mwakatumbula/production
      
    - name: Change permissions 
      if: github.ref == 'refs/heads/master'
      run: chmod -R 777 /home/mwakatumbula/production
      
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.actor }} just triggered ${{ github.event_name }} event on ${{ github.repository }} Action Status ${{job.status}}.  

      
     
    
 
